["module", [["import", [], {"area": [[7, 1], [7, 10]], "path": ["sys"], "factor": true, "identifier": "sys"}], ["import", [], {"area": [[8, 1], [8, 36]], "path": ["fault", "vector", "recognition"], "relative": 0, "factor": true, "identifier": "recognition"}], ["import", [], {"area": [[9, 1], [9, 32]], "path": ["fault", "system", "process"], "relative": 0, "factor": true, "identifier": "process"}], ["data", [], {"identifier": "required", "area": [[11, 1], [14, 1]]}], ["data", [], {"identifier": "restricted", "area": [[16, 1], [16, 15]]}], ["function", [["type", [], {"syntax": "process.Exit", "reference": "process.Exit", "area": [[18, 37], [18, 48]]}], ["parameter", [["type", [], {"syntax": "process.Invocation", "reference": "process.Invocation", "area": [[18, 14], [18, 31]]}]], {"identifier": "inv", "area": [[18, 10], [18, 35]]}]], {"identifier": "main", "area": [[18, 1], [44, 44]], "documented": [[19, 2], [22, 2]]}]], {"identifier": "/x/canonical/integration/system/factors/error.py", "area": [[1, 1], [44, 0]], "documented": [[1, 1], [6, 3]], "source-encoding": "utf-8"}]