[[["syntax_divisor"], ["frame_divisor"], ["Frame", "area"], ["seq"], ["k"]], [[null, {"syntax": "48*\"\u2504\"", "area": [[8, 25], [8, 32]]}], [null, ""], [], [{"syntax": "{\n\t\t'function': 'control',\n\t\t'factor': \"fault.system.process\",\n\t\t'resource': \"/python/lib/fault/system/process.py\",\n\t\t'area': 731,\n\t\t'source': \"    Fork.trap(main, *args, **kw)\",\n\t}", "area": [[63, 2], [69, 2]]}, {"syntax": "{\n\t\t'function': 'trap',\n\t\t'factor': \"fault.system.process\",\n\t\t'resource': \"/python/lib/fault/system/process.py\",\n\t\t'area': 635,\n\t\t'source': \"return controller(*args, **kw) # Process replacement point.\",\n\t}", "area": [[69, 5], [75, 2]]}, {"syntax": "{\n\t\t'function': 'main',\n\t\t'factor': \"fault.system.bin.subexec\",\n\t\t'resource': \"/python/lib/fault/system/bin/subexec.py\",\n\t\t'area': 123,\n\t\t'source': \"module_path = inv.args[count] # No module specified?\"\n\t}", "area": [[75, 5], [81, 2]]}], {"syntax": "{\n\t'exception': \"IndexError\",\n\t'message': \"list index out of range\"\n}", "area": [[83, 5], [86, 1]]}]]